# Online Continual Learning with Hyperneurons


In [1]:
import numpy as np
import torch
from torch.nn.functional import linear

In [3]:
np.exp(1j * 2 * np.pi * np.random.random((4, 5)))

array([[ 0.3513038 +0.93626152j, -0.84848026+0.52922702j,
        -0.53982396+0.84177794j, -0.9733627 -0.22927071j,
         0.19482098-0.98083882j],
       [-0.56406122-0.82573297j, -0.97126753-0.23799029j,
         0.75866667+0.651479j  , -0.3818321 -0.92423171j,
         0.52723084-0.8497221j ],
       [-0.98882294+0.14909457j, -0.33023579-0.94389847j,
        -0.84821712-0.52964868j,  0.65786056-0.75313975j,
        -0.21067962-0.97755516j],
       [-0.92238701-0.38626701j,  0.92655819+0.37615146j,
         0.82265835-0.56853605j,  0.32927153-0.94423528j,
         0.85004516-0.52670981j]])

In [7]:
def softmax(x):
    '''Helper function to compute softmax in a numerically stable way.'''
    max_x = np.max(x)
    return np.exp(x - max_x) / np.sum(np.exp(x - max_x))

In [28]:
def lazy_bubblesort(x, order):
    '''
    Update the ordering (order) of a list (x) using a single upward and downward pass of bubblesort.
    Order should be decreasing to represent rankings, while list elements remain in place.
    Single-pass, lazy bubblesort gives a simple way to do incremental sorting over repeated timesteps in O(n).
    '''
    N = len(x)

    # Push smaller elements further down the rankings.
    for i in range(N - 1):
        # Swap orders if the value at the current rank is smaller than that at the next rank.
        if x[order[i]] < x[order[i + 1]]:
                order[i], order[i + 1] = order[i + 1], order[i]

    # # Pull larger elements further up the rankings.
    # for i in range(N - 1):
    #     # Swap orders if the value at the current rank is larger than that at the previous rank.
    #     if x[order[-i]] > x[order[-i - 1]]:
    #         order[-i], order[-i - 1] = order[-i - 1], order[-i]

    # Order of list should be stored by whatever called this so incremental sorting can continue on the next timestep.
    return order

In [29]:
x = np.random.random_sample(10)
x

array([0.64506513, 0.82762656, 0.23912974, 0.63396832, 0.75119008,
       0.16947031, 0.5745722 , 0.35525883, 0.47287316, 0.55571657])

In [30]:
order = np.arange(10)
order

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
order = lazy_bubblesort(x, order)
order

array([1, 0, 4, 3, 6, 7, 8, 9, 2, 5])

In [32]:
x[order]

array([0.82762656, 0.64506513, 0.63396832, 0.75119008, 0.23912974,
       0.5745722 , 0.35525883, 0.47287316, 0.55571657, 0.16947031])

In [ ]:
# Define a dense associate memory (DAM) that stores complex-valued hyperdimensional vectors and learn online.
class DAM:
    def __init__(self, N, D):
        # N prototypes, D dimensions, scale random correlations to have unit normal similarity distribution.
        self.N = N
        self.D = D
        self.scale = np.sqrt(2. / D)

        # N prototype codes sit on the D-dimensional unit complex hypertorus.
        self.prototypes = np.exp(1j * 2 * np.pi * np.random.random((N, D)))

        #
        self.outputcode = np.exp(1j * 2 * np.pi * np.random.random((D, N)))

        # Track prototype usage frequencies and rankings for Zipf homeostatic regularization.
        self.frequency = 1. / N * np.ones((N, 1))
        self.rankorder = np.arange(1, N + 1)

    def recall(self, query):
        # Find real-valued similarity scores for the query against every prototype in memory,
        # scaled so that random complex hypervectors will have unit normal similarity.
        similarity = self.scale * np.real(np.matmul(np.conj(self.prototypes), query))

        # Apply softmax nonlinearity
        assignment = softmax(self.inv_temp * similarity)

        # Track

# Building Intuition with Character Prediction in Simplified English Wikipedia
Read in a condensed version of the English Wikipedia as a source of text and track everything character-by-character. Each character gets its own complex-valued hypervector representation, initialized randomly but converging on being predictive of context through learning.



In [87]:
from collections import Counter

# Open the file and iterate over its lines automatically
with open('../../data/AllCombined.txt', 'r', encoding='utf-8') as file:
    all_text = file.read()
    char_counts = Counter(all_text)

In [88]:
# Establish character hypervector dictionary.
N_char = len(char_counts)
N_dims = 1024
char_dict = np.exp(1j * 2 * np.pi * np.random.random((N_dims, N_char)))

# Return the appropriate character hypervector from the dictionary.
def char_vctr(char):
    char_idx = np.where(np.array(list(char_counts.keys())) == char)[0]
    return char_dict[:,char_idx]

In [90]:
# Character hypervectors should be predictive of each other in sequence.
# Establish default phasor to predict hypervector rotations.
char_init = np.exp(1j * 2 * np.pi * np.random.random((N_dims, 1)))
char_step = np.exp(1j * 2 * np.pi * np.random.random((N_dims, 1)))
keep_frac = 0.9

# Define update rule for tracking running histories of character sequences.
def advance_char(char_pred, char_true):
    # The true character hypervector was predicted by the previous bound superposition
    # character sequence. Average the prediction and the truth before advancing.
    char_mean = keep_frac * char_pred + (1 - keep_frac) * char_true

    # Advance by rotation through binding with the "step" hypervector before renormalizing.
    char_next = char_mean * char_step
    char_next = char_next / np.abs(char_next)
    return char_next

In [91]:
len(all_text)

178255102