# Online Continual Learning with Hyperneurons


In [1]:
import numpy as np
import torch
from torch.nn.functional import linear

In [3]:
np.exp(1j * 2 * np.pi * np.random.random((4, 5)))

array([[ 0.3513038 +0.93626152j, -0.84848026+0.52922702j,
        -0.53982396+0.84177794j, -0.9733627 -0.22927071j,
         0.19482098-0.98083882j],
       [-0.56406122-0.82573297j, -0.97126753-0.23799029j,
         0.75866667+0.651479j  , -0.3818321 -0.92423171j,
         0.52723084-0.8497221j ],
       [-0.98882294+0.14909457j, -0.33023579-0.94389847j,
        -0.84821712-0.52964868j,  0.65786056-0.75313975j,
        -0.21067962-0.97755516j],
       [-0.92238701-0.38626701j,  0.92655819+0.37615146j,
         0.82265835-0.56853605j,  0.32927153-0.94423528j,
         0.85004516-0.52670981j]])

In [7]:
def softmax(x):
    '''Helper function to compute softmax in a numerically stable way.'''
    max_x = np.max(x)
    return np.exp(x - max_x) / np.sum(np.exp(x - max_x))

In [28]:
def lazy_bubblesort(x, order):
    '''
    Update the ordering (order) of a list (x) using a single upward and downward pass of bubblesort.
    Order should be decreasing to represent rankings, while list elements remain in place.
    Single-pass, lazy bubblesort gives a simple way to do incremental sorting over repeated timesteps in O(n).
    '''
    N = len(x)

    # Push smaller elements further down the rankings.
    for i in range(N - 1):
        # Swap orders if the value at the current rank is smaller than that at the next rank.
        if x[order[i]] < x[order[i + 1]]:
                order[i], order[i + 1] = order[i + 1], order[i]

    # # Pull larger elements further up the rankings.
    # for i in range(N - 1):
    #     # Swap orders if the value at the current rank is larger than that at the previous rank.
    #     if x[order[-i]] > x[order[-i - 1]]:
    #         order[-i], order[-i - 1] = order[-i - 1], order[-i]

    # Order of list should be stored by whatever called this so incremental sorting can continue on the next timestep.
    return order

In [29]:
x = np.random.random_sample(10)
x

array([0.64506513, 0.82762656, 0.23912974, 0.63396832, 0.75119008,
       0.16947031, 0.5745722 , 0.35525883, 0.47287316, 0.55571657])

In [30]:
order = np.arange(10)
order

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
order = lazy_bubblesort(x, order)
order

array([1, 0, 4, 3, 6, 7, 8, 9, 2, 5])

In [32]:
x[order]

array([0.82762656, 0.64506513, 0.63396832, 0.75119008, 0.23912974,
       0.5745722 , 0.35525883, 0.47287316, 0.55571657, 0.16947031])

In [ ]:
# Define a dense associate memory (DAM) that stores complex-valued hyperdimensional vectors and learn online.
class DAM:
    def __init__(self, N, D):
        # N prototypes, D dimensions, scale random correlations to have unit normal similarity distribution.
        self.N = N
        self.D = D
        self.scale = np.sqrt(2. / D)

        # N prototype codes sit on the D-dimensional unit complex hypertorus.
        self.prototypes = np.exp(1j * 2 * np.pi * np.random.random((N, D)))

        #
        self.outputcode = np.exp(1j * 2 * np.pi * np.random.random((D, N)))

        # Track prototype usage frequencies and rankings for Zipf homeostatic regularization.
        self.frequency = 1. / N * np.ones((N, 1))
        self.rankorder = np.arange(1, N + 1)

    def recall(self, query):
        # Find real-valued similarity scores for the query against every prototype in memory,
        # scaled so that random complex hypervectors will have unit normal similarity.
        similarity = self.scale * np.real(np.matmul(np.conj(self.prototypes), query))

        # Apply softmax nonlinearity
        assignment = softmax(self.inv_temp * similarity)

        # Track

In [46]:
from collections import Counter

# Open the file and iterate over its lines automatically
with open('../../data/AllCombined.txt', 'r', encoding='utf-8') as file:
    char_counts = Counter(file.read())
    lines = file.readlines()
    # for line in file:
    #     # .rstrip('\n') removes the trailing newline character from each line
    #     clean_line = line.rstrip('\n')
    #     print(clean_line)
lines = [line.rstrip('\n') for line in lines]
lines = [line for line in lines if line != '']
line_len = np.array([line.count(' ') for line in lines])

In [41]:
lines[np.where(line_len == 4)[0][100]]

'Some more controversial treatments include'

In [42]:
all_char = set()
for line in lines:
    all_char.update(line)

In [47]:
char_counts

Counter({' ': 28823262,
         'e': 16107566,
         'a': 12013383,
         't': 10647031,
         'n': 9978134,
         'i': 9891872,
         'o': 9648296,
         'r': 8719686,
         's': 8582523,
         'h': 6139997,
         'l': 5453848,
         'd': 4858714,
         'c': 3834801,
         'u': 3426994,
         'm': 3366674,
         'f': 2645838,
         'p': 2409668,
         'g': 2339846,
         'y': 2150489,
         'w': 2106197,
         '\n': 2052699,
         '.': 2034090,
         'b': 1890557,
         ',': 1640826,
         'v': 1266076,
         'k': 917240,
         '1': 874756,
         'T': 770508,
         'S': 739702,
         '0': 729174,
         '"': 672609,
         'A': 670938,
         '2': 641191,
         'C': 576876,
         'I': 549955,
         '9': 517533,
         'M': 484366,
         'H': 438590,
         'B': 417736,
         'P': 375492,
         ')': 307086,
         '(': 306772,
         '-': 306482,
         'D': 287827,
  

In [50]:
min(char_counts.values())

1

In [53]:
char_counts['@']

98

In [62]:
np.sum(np.array(list(char_counts.values())) > 10)

1162

In [58]:
np.array(list(char_counts.values()))

array([2052699,  670938, 2409668, ...,       2,       1,       1])

In [66]:
np.sort(np.array(list(char_counts.keys())))[:1000]

array(['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+',
       ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
       'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_',
       '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
       'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
       'z', '{', '|', '}', '~', '\x80', '\x92', '\x9d', '\xa0', '¡', '¢',
       '£', '¤', '¥', '§', '¨', '©', 'ª', '«', '¬', '\xad', '®', '¯', '°',
       '±', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '»', '¼', '½',
       '¾', '¿', 'À', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Æ', 'Ç', 'È', 'É', 'Ê',
       'Ë', 'Ì', 'Í', 'Î', 'Ð', 'Ñ', 'Ò', 'Ó', 'Ô', 'Õ', 'Ö', '×', 'Ø',
       'Ù', 'Ú', 'Û', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å',
       'æ', 'ç', 'è', 'é', 'ê', 'ë', 'ì', 'í', 'î', 'ï', 

In [67]:
# Establish character hypervector dictionary.
N_char = len(char_counts)
N_dims = 1024
char_dict = np.exp(1j * 2 * np.pi * np.random.random((N_dims, N_char)))

array([[ 0.26125386+0.96527013j,  0.79009335-0.61298655j,
         0.94760265-0.31945144j, -0.18811624-0.98214677j,
         0.89968408+0.43654158j],
       [-0.61438419-0.78900702j,  0.43654397-0.89968292j,
         0.84848416-0.52922077j,  0.99845762-0.05551913j,
         0.08717148-0.99619332j],
       [ 0.05595544+0.99843327j,  0.96600742-0.25851434j,
         0.28449731+0.95867684j,  0.92856396+0.37117243j,
         0.93355055+0.35844576j],
       [-0.83556529-0.54939115j, -0.99526237-0.09722557j,
        -0.99601769-0.08915581j,  0.39815403+0.91731857j,
         0.00909672-0.99995862j]])

In [ ]:
# Character hypervectors should be predictive of each other in sequence.
# Establish default phasor to predict hypervector rotations.
char_step = np.exp(1j * 2 * np.pi * np.random.random((N_dims, 1)))
